# Generated by Django 4.0.2 on 2022-02-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='наименование')),
                ('short_title', models.CharField(blank=True, default='', max_length=64, verbose_name='краткое наименование')),
                ('description', models.TextField(blank=True, default='', max_length=256, verbose_name='описание')),
                ('version', models.CharField(max_length=10, verbose_name='версия')),
                ('valid_from', models.DateTimeField(verbose_name='действует с')),
            ],
            options={
                'verbose_name': 'catalog',
                'verbose_name_plural': 'catalogs',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='код')),
                ('value', models.CharField(max_length=126, verbose_name='значение')),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier_api.catalog', verbose_name='идентификатор родительского справочника')),
            ],
            options={
                'verbose_name': 'catalog item',
                'verbose_name_plural': 'catalog items',
            },
        ),
    ]
